var crunchyrollShows = ["07 Ghost", "11eyes", "5 Centimeters per Second", "91 Days", 
"A Bridge to the Starry Skies - Hoshizora e Kakaru Hashi", "A Dark Rabbit has Seven Lives",
"A Lull in the Sea", "Aachi & Ssipak", "Ace Attorney", "Ace of the Diamond",
"Active Raid", "Actually, I am", "Ah my Buddha!!", "Ai-Mai-Mi", 
"Ai-Mai-Mi Mousou Catastrophe", "Air Master", "AIURA", "Akagi", "Akame ga Kill!",
"AKB0048", "Alderamin on the Sky", "ALDNOAH.ZERO", "ALL OUT!!", "Amagi Brilliant Park",
"Amanchu!", "Amnesia", "Ange Vierge", "Angel Beats", "Anime De Training! Ex", 
"ANISAVA", "Anne-Happy", "Ano Natsu de Matteru", "Anohana: The Flower We Saw That Day",
"Another", "Anti-Magic Academy: The 35th Test Platoon", "Aoharu x Machinegun", 
"AOKANA: Four Rhythm Across the Blue", "Aooni The Blue Monster", 
"Arakawa Under the Bridge", "Arata the Legend", "ARGEVOLLEN", "Arpeggio of Blue Steel",
"Asura Cryin'", "Attack on Titan", "B-PROJECT", "Baby Steps", "Bakemonogatari", 
"BAKUMATSU GIJINDEN ROMAN", "BAKUON!!", "Bananya", "Battle Girls - Time Paradox",
"BBK/BRNK", "Beautiful Bones - Sakurako's Investigation-", "Beelzebub", 
"Beserk", "Beyblade", "Beyblade: Beywheelz", "Beyblade: Metal Fury", 
"Beyblade: Metal Fusion", "Beyblade: Metal Masters", "Beyond the Boundary", 
"BIG ORDER", "Black Bullet", "Black Jack", "Blade and Soul", "Bladedance of the Elementalers", 
"BLASSREITER", "Blast of Tempest", "Bleach", "Bloodivores", "Blue Exorcist", 
"Blue Spring Ride", "Blue Submarine No. 6", "Bodacious Space Pirates", 
"Boku-no-imoutowa'Osaka-okan'", "Bokurano", "BONJOUR - Sweet Love Patisserie", 
"BONO BONO", "Bottom Biting Bug", "Brave 10", "Brave Beats", "Brave Witches", 
"Break Ups", "Broken Blade", "BROTHERHOOD FINAL FANTASY XV", "Brynhildr in the Darkness", 
"BTOOOM!", "Bungo Stray Dogs", "Campione!", "Canvas 2: Niji Iro no Sketch", 
"Captain Earth", "Captain Harlock", "Cardcaptor Sakura", "Cardcaptor Sakura: The Movie", 
"Cardfight Vanguard", "Cardfight!! Vanguard Asia Circuit", "Cardfight!! Vanguard G", 
"Cardfight!! Vanguard Legion Mate", "Cardfight!! Vanguard Link Joke", "Case Closed", 
"Cat God", "Cat's Eye", "Celestial Method", "Cerberus", "Ceres, Celestial Legend", 
"Chaika - The Coffin Princess-", "Champion Joe 2", "Chance Pop Session", "Charlotte", 
"Cheating Craft", "Chi's Sweet Home - Chi's New Address", "Chihayafuru", 
"Chitose Got You!", "Chronicles of the Going Home Club", "Classroom Crisis", 
"Comet Lucifer", "Comical Psychosomatic Medicine", "Cowboy Bebop", "Crane Game Girls", 
"Crunchycast", "Crunchyroll Collection", "Crunchyroll Convention Highlights", 
"Cute High Earth Defense Club LOVE!", "Cubicle Detective Inaba", "D.Gray-man HALLOW", 
"Da Capo III", "Dai-Shogun - Great Revolution", "Dallos", "Danchigai", 
"Day Break Illusion", "DAYS", "DD Fist of the North Star", "DearS", "Deltora Quest", 
"DEMIAN", "Demon King Daimao", "Demonbane", "DENKI-GAI", "DEVIL SURVIVOR 2 THE ANIMATION", 
"Diabolik Lovers", "DIABOLIK LOVERS II: MORE,BLOOD", "Digimon Adventure", 
"Digimon Adventure 02", "Digimon Adventure tri", "Digimon Frontier", "Digimon Tamers", 
"Digimon Xros Wars", "DNA^2", "Dog & Scissors", "Dog Days", "Donyatsu", 
"Dororo Motion Magazine", "Double Hard", "DRAGON COLLECTION", "Dragon Crisis", 
"DRAMAtical Murder", "DREAM FESTIVAL!", "Durarara", "Dusk Maiden of Amnesia", "Ebiten", 
"Ef - A Tale of Melodies", "Ef - A Tale of Memories", "Encouragement of Climb", 
"Enraged to the Unidentified", "ERASED", "Erin", "ETOTAMA", "Eyeshield 21", 
"Fafner Exodus", "Fairy Musketeers", "Fairy Tail", "Familiar of Zero F", "Fantasista Doll", 
"Fantastic Adventures of Unico", "Fantastic Detective Labyrinth", 
"Fate/kaleid liner PRISMA ILLYA", "Fate/stay night", "Fate/Zero", "FIRST LOVE MONSTER", 
"Fist of the North Star", "Fist of the North Star: The Movie", "Flame of Recca", 
"FLIP FLAPPERS", "Flowers of Evil", "Flying Witch", "Folktales from Japan", 
"Food Wars! Shokugeki no Soma", "Free! - Iwatobi Swim Club", "Fullmetal Alchemist: Brotherhood", 
"Fushigi Yugi", "Fushigi Yugi OVA", "Fushigi Yugi: Eikoden", "Future Card Buddyfight", 
"GA Geijutsuka Art Design Class", "Gakuen Handsome", "Gakuen Heaven", "Galaxy Express 999", 
"Galaxy High School", "Galilei Donna", "Gankutsuou", "Garakowa -Restore the World-", 
"Gargantia on the Verdurous Planet", "Gatchaman Crowds", "GATE", "gdgd Fairies", 
"Genshiken Second Season", "Ghastly Prince Enma Burning Up", "Ghost Slayers Ayashi", 
"Ghost Stories", "Gifu Dodo!! Kanetsugu and Keiji", "Gingitsune: Messenger Fox of the Gods", 
"Gintama", "Girl Friend BETA", "Girl's High", "GIRLS und PANZER", "GJ CLUB", "Glass Mask", 
"GLASSLIP", "Go Lion", "God Eater", "God Mars", "Golden Time", "Gourmet Girl Graffiti", 
"Grimgar of Fantasy and Ash", "Group Watch", "GTO - The Animation", "Gugure! Kokkuri-san", 
"Gunbuster 2", "Gunslinger Stratos", "Gurren Lagann", "H2O: Footpritns in the Sand", 
"Hackadoll the Animation", "Haikyu!!", "Hajime no Ippo: The Fighting!", 
"Hakkenden: Eight Dogs of the East", "Hakone-chan", "Hakuoki Reimeiroku", "Hekuoki Season 1", 
"Hamatora", "Hanamaru Kindergarten", "Hanasakeru Seishonen", "Hanasaku Iroha", 
"HaNaYaMaTa", "Happiness!", "HATSUNE MIKU EXPO 2014 - New York", "Haven't You Heard? I'm Sakamoto", 
"Hayate the Combat Butler!", "Hayate the Combat Butler! (Season 1 & 2)", 
"HENNEKO - The Hentai Prince and the Story Cat", "HEROBANK", "HEROMAN", "HEYBOT!", 
"Hi-sCool! Seha Girls", "High School Fleet", "Hiiro No Kakera", "Himegoto", 
"Himouto! Umaru-chan", "hitorinoshita - The Outcast", "Holy Knight", "Horizon in the Middle of Nowhere", 
"Horror News", "Hourou Musuko Wandering Son", "Hozuki no Reitetsu", "Humanity Has Declined", 
"Hundrd", "Hunter x Hunter", "Hyakko", "I Can't Understand What My Husband Is Saying", 
"I've Always Liked You", "Inferno Cop", "Infinite Stratos", "Interlude", "Inu x Boku Secret Service", 
"Inugami-san to Nekoyama-san", "INVADERS of the REOKUJYOMA!?", "Investor Z (Motion Manga)", 
"Is It Wrong to Try to Pick Up Girls in a Dungeon?", "Is the Order a Rabbit?", "ISUCA", 
"Ixion Saga DT", "Izetta: The Last Witch", "Japanese Anime Classic Collection", "Jin Roh", "JK-MESH!", 
"JoJo's Bizarre Adventure", "JOKER", "JOKER GAME", "Jubei-chan: The Ninja Girl", "Kaasan Mom's Life", 
"Kaede New Town", "KAGEWANI", "Kaiji", "KAIJU GIRLS", "Kamigami no Asobi", "Kamisama Dolls", 
"Kanamemo", "KanColle", "Kanojo ga Flag wo Oraretara (If Her Flag Breaks)", "Keijo!!!!!!!!", 
"Kids on the Slope", "Kiitaro's yokai picture diary", "Kill la Kill", "Kimi ni Todoke - From Me To You", 
"KINMOZA!", "Kite Liberator", "KIZNAIVER", "Knuspercast", "Koihime Musou", "Kokoro Connect", 
"Komori-san Can't Decline!", "Kono Aozora ni Yakusoku wo", "KONOSUBA - God's blessing on this wonder world", 
"Kotoura-San", "Kurokan", "Kuroko's Basketball", "Kyousougiga", "La Corda d'Oro ~primo passo~ and ~secondo passo~", 
"La corda d'oro -Blue Sky-", "La storia della Arcana Famiglia", "Lady Death", "Lance N' Masques", 
"Leiji Matsumoto's OZMA", "Library War", "Lilpri", "Lily C.A.T", "Linebarrels of Iron", "LiSA TV", 
"Listen to Me, Girls, I'm Your Father!", "Little Busters!", "Little Nemo: Adventures in Slumberland", 
"Locodol", "Log Horizon", "Looking Up at the Half-Moon", "Lost Universe", "Love Lab", "Love Live! School Idol Project", 
"Love Stage!!", "Love, Chunibyo & Other Delusions", "Love, Chunibyo & Other Delusions - Heart Throb -", 
"Lovely Muuuuuuuco!", "LUPIN THE 3rd PART4", "Lupin the Third Part 1", "Lupin the Third Part 2", 
"Lupin the Third Part 3", "Lychee Light Club", "Magi", "Magic Kaito 1412", "Magic-Kyun! Renaissance", 
"MAGICA WARS", "Magical Girl Raising Project", "Magical Play", "Magical Somera-chan", "Magical Warfare", 
"Magimoji Rurumo", "Mahou Shoujo Nante Mouiidesukara", "Mahou Shoujo? Naria Girls", "Majestic Prince", 
"Majin Bone", "Makai Ouji: Devils and Realist", "makuranodanshi", "Mangirl!", "Maoyu", "Mashioiro Symphony", 
"Mazinger Edition Z", "Mazinkaiser SKL", "Medaka Box", "MEGANEBU!", "MEKAKUCITY ACTORS", "Military!", 
"Million Doll", "Milpom", "Miracle Train", "Miss Bernard said.", "Miss Machiko", "Miss Monochrome - The Animation", 
"Mizu no Kotoba", "Mob Psycho 100", "Mobile Suit GUNDAM Iron Blooded Orphans", 
"MOBILE SUIT GUNDAM UNICORN RE:0096", "Momo Kyun Sword", "momokuri", "Monogatari Second Season", 
"Mononoke", "Monster Hunter Stories: Ride On", "MONSTER MUSUME EVERYDAY LIFE WITH MONSTERS", 
"Monthly Girls' Nozaki-kun", "Moritasan wa Mukuchi", "Moyashimon", "Mr. Osomatsu", "Muromi-san", 
"MUSHI-SHI", "Mushi-Uta", "Mushibugyo", "My Little Monster", "MY Love STORY!!", 
"My Mental Choices are Completely Interfering with my School Romantic Comedy", 
"My Teen Romantic Comedy SNAFU", "Oreigairu", "Myriad Colors Phantom World", "Myself; Yourself", 
"Mysterious Girlfriend X", "Nagi no Asukara (Nagi-Asu: A Lull in the Sea)", "Naked Wolves", "Nanana's Buried Treasure", 
"NANBAKA", "Naruto", "Naruto Shippuden", "NARUTO Spin-Off: Rock Lee & His Ninja Pals", 
"NATSU NO ARASHI !", "Natsume Yujin-cho", "Natsume Yujin-cho Go", "Natsume Yujin-cho Shi", "Natsuyuki Rendezvous", 
"Nazotokine", "Nekomonogatari Black", "Neo Angelique Abyss", "NEW GAME!", "Night Raid 1931", 
"Ninja Girl & Samurai Master", "Nnija Nonsense", "Nisekoi", "Nisemonogatari", "No Game No Life", 
"No. 6", "Noblesse: Awakening", "Nobunaga Concerto", "Nobunaga the Fool", "Nobunagan", "Nogizaka Haruka no Himitsu", 
"Nogizaka Haruka no Himitsu - Purezza -", "Non Non Biyori", "Nurse Witch KOMUGI R", "Nyanbo!", 
"Nyarko-san: Another Crawling Chaos", "Occult Academy", "Ojisan and Marshamallow", "One Piece", 
"One Week Friends", "Onee-chan ga Kita", "Onimusha: Dawn of Dreams", "Ooya-san wa Shisunki!", 
"Orange", "ORECA BATTLE", "Oreimo", "Orenchi no Furo Jijo", "Oreshura", "Otome Yokai Zakuro", 
"Our Home's Fox Deity", "Outbreak Company", "OWARIMONOGATARI", "OZMAFIA!!", "Pan de Peace!", "PandoraHearts", 
"Parasyte -the maxim-", "Peeping Life", "Peeping Life TV Season 1??", "Persona4 the Golden ANIMATION", "PERSONA5 the Animation -THE DAY BREAKERS-", 
"PES: Peace Eco Smile", "Phantasy Star Online 2 The Animation", "Phantom Thief Reinya", 
"Phi Brain", "Photo Kano", "Pita-Ten", "Plastic Memories", "Please tell me! Galko-chan", 
"Polar Bear Cafe", "Poyopoyo", "Pretty Cure", "Princess Knight", "Princess Nine", "Problem Children are Coming from Another World, aren't they?", 
"PSYCHO-PASS", "Puella Magi Madoka Magica", "PUNCH LINE", "Puzzle & Dragons X", "Qualidea Code", 
"R.O.D.", "Rail Wars!", "Ramen Fighter Miki", "Re-Kan!", "Re:ZERO -Starting Life in Another World-", 
"Re:ZERO -Starting Life in Another World- Shorts", "REBORN!", "Recorder and Randsell", "ReLIFE", 
"Rewrite", "RIN-NE", "Ringing Bell", "Rio Rainbow Gate", "Ristorante Paradiso", "Robot Girls Z", 
"Rokka -Braves of the Six Flowers-", "Rowdy Sumo Wrestler Matsutaro", "Rozen Maiden", "Rozen Maiden Zurückspulen", 
"Ruroni Kenshin", "RWBY", "Sabagebu! -Survival Game Club!-", "Saekano -How to Raise a Boring Girlfriend-", 
"Sailor Moon Crystal", "Saint Seiya - Soul of Gold", "Saint Seiya Hades", "Saint Seiya Omega", "Saint Seiya The Lost Canvas", 
"Saint Seiya: Sanctuary", "Saki", "Saki Episode of Side A", "Sakura Trick", "Samurai Flamenco", 
"Samurai Jam-Bakumatsu Rock", "Samurai Pizza Cats", "Samurai Warriors", "Say 'I Love You'", 
"School Days", "SCHOOL-LIVE!", "Schwarzes Marken", "Scorching Ping Pong Girls", "Sea Prince and the Fire Child", 
"Seitokai No Ichizon - Student Councils Discretion", "Sekai Ichi Hatsukoi - World's Greatest First Love", 
"Sekko Boys", "Sengoku Collection (Parallel World Samurai)", "Senyu", "Servant x Service", 
"Shamanic Princess", "She and Her Cat -Everything Flows-", "Sherlock Hound", "Shin Atashinchi", 
"Shin Koihime Musou", "Shin Koihime Musou - Otome Tairan", "Shin Sekai Yori (From the New World)", 
"Shingu: Secret of the Stellar Wars", "SHIROBAKO", "SHOKU-KING (Motion Manga)", "Shonen Ashibe GO! GO! Goma-chan", 
"Show By Rock!!", "Showa Genroku Rakugo Shinju", "Shugo Chara", "Silver Spoon", "Sin The Movie", 
"SKET Dance", "Sketchbook ~full color's~", "Skip Beat!", "Slam Dunk", "Soni-Ani: SUPER SONICO THE ANIMATION", 
"Sound of the Sky", "Sound! Euphonium", "Hibike! Euphonium", "Space Adventure Cobra", "Space Brothers", 
"SPACE PATROL LULUCO", "Space Pirate Mito", "Sparrow's Hotel", "Squid Girl", "Star Driver", 
"Stella Women’s Academy, High School Division Class C3", "Straight Title Robot Anime", 
"Strange+", "Street Fighter II The Animated Movie", "Strike the Blood", "Sunday Without God", 
"Super Robot Wars: Original Generation", "Sweet Blue Flowers", "sweetness and lightning", 
"Sword Art Online", "Symphogear", "Tabimachi Lateshow", "Taboo Tattoo", "Takamiya Nasuno Desu!", 
"Tanaka-kun is Always Listless", "Tantei Team KZ Jiken Note", "Tari Tari", "Teekyu", "Tegami Bachi Letter Bee", 
"Tenjho Tenge", "TERRAFORMARS", "Tesagure! Bukatsumono", "The Ambition of Oda Nobuna", "The Ancient Magus' Bride", 
"The Asterisk War", "The Comic Artist and His Assistants", "The Diary of Ochibi (Motion Manga)", 
"The File of Young Kindaichi Returns", "The Fruit of Grisaia", "The Galaxy Railways: A Letter from the Abandoned Planet", 
"The Highschool Life of a Fundanshi", "The Idol Master", "The Irregular at Magic High School", 
"The Kawaii Complex Guide to Manors and Hostel Behavior", "The Knight in the Area", "The Live Show", 
"The Lost Village", "The Melody of Oblivion", "The Morose Mononokean", "The Nameko Families", 
"The Perfect Insider", "The Pet Girl of Sakurasou", "The Pilot's Love Song", "The Place Promised In Our Early Days", 
"The Prince of Tennis II", "The Prince of Tennis II OVA vs Genius 10", "The Princess and the Pilot", 
"The Rose of Versailles", "The Severing Crime Edge", "The Tenth Prism (Motion Manga)", "The Testament of Sister New Devil", 
"The Tower of DRUAGA -the Aegis of URUK-", "The Tower of DRUAGA -the Sword of URUK-", 
"THE UNLIMITED Hyobu Kyosuke", "The World God Only Knows", "The World is Still Beautiful", "This Art Club Has a Problem!", 
"This Boy is a Professional Wizard", "This Boy Suffers from Crystalization", "Thunderbolt Fantasy", 
"Tiger Mask W", "Time Bokan 24", "Time of Eve", "TO BE HERO", "Tonari no Seki-kun: The Master of Killing Time", 
"Tonkatsu DJ Agetaro", "Tono to Issho", "Toradora!", "Toriko", "Total Eclipse", "Touken Ranbu - Hanamaru", 
"Toward the Terra", "Traveling Daru", "Triage X", "Tribe Cool Crew", "Trickster", "TRINITY SEVEN", 
"Tsukimonogatari", "Tsuritama", "Twin Angel: Twinkle Princess", "Twin Star Exorcists", "Un-Go", 
"Unico In the Island of Magic", "Unlimited Fafnir", "Upotte!!", "Urawa no Usagi-chan", "Usagi Drop", 
"Usakame", "Ushio and Tora", "Uta no Prince Sama", "Utakoi", "Utawarerumono The False Faces", 
"Valerian and Laureline", "Vividred Operation", "Voices of a Distant Star", "Wagamama High Spec", 
"Wagnaria!!", "Wakaba Girl", "Wakakozake", "Wake Up, Girls!", "Walkure Romanze", "Wanna be the Strongest in the World", 
"WATAMOTE ~No Matter How I Look at It, It’s You Guys Fault I’m Not Popular", "We, Without Wings - under the innocent sky", 
"Web Ghosts PiPoPa", "When Supernatural Battles Become Commonplace", "White Album", "White Album 2", 
"Wish Upon the Pleiades", "Witch Craft Works", "Wizard Barristers", "Wolf Girl and Black Prince", 
"Wonder Momo", "Wooser's Hand-to-Mouth Life", "Wooser's Hand-to-Mouth Life: Phantasmagoric Arc", 
"World Break: Aria of Curse for a Holy Swordsman", "World Conquest Zvezda Plot", "World Fool News", 
"World Trigger", "WWWW.WAGNARIA!!", "Yakitate!! Japan", "Yamada-kun and the Seven Witches", 
"Yamishibai: Japanese Ghost Stories", "Yokuwakaru Gendai Maho", "Yona of the Dawn", "Yonna in the Solitary Fortress", 
"You and Me", "You and Me 2", "You're Being Summoned, Azazel", "Young Black Jack", "Your lie in April", 
"Yowamushi Pedal", "Yu-Gi-Oh!", "Yu-Gi-Oh! 5D's", "Yu-Gi-Oh! GX", "YUKI YUNA IS A HERO", "Yuri!!! On ICE", 
"Yurumates3Dei", "YuruYuri", "YUYUSHIKI", "Z/X IGNITION", "Zapuni", "Zatch Bell!", "Zettai Boei Leviatan", 
"Zombie Loan"];

var netflixShows = ["The Seven Deadly Sins", "Attack on Titan", "Fairy Tail", "Magi: Adventure of Sinbad", 
"Sword Art Online", "Ruroni Kenshin", "Blue Exorcist", "Ajin: Demi-Human", "Naruto", "Robotech", 
"Bleach", "Magi: The Kingdom of Magic", "Sword Art Online II", "Kuromukuro", "Soul Eater", 
"Ouran High School Host Club", "Gurren Lagann", "Your lie in April", "Pokemon: Indigo League", 
"Magi: The Labyrinth of Magic", "Black Butler", "Rosario + Vampire", "The Irregular at Magic High School", 
"Knights of Sidonia", "Durarara!!", "Aldnoah.Zero", "K", "InuYasha", "Durarara!!X2", "Gargantia on the Verdurous Planet", 
"Moribito: Guardian of the Spirit", "Mushi-Shi", "Nura: Rise of the Yokai Clan", "Digimon Adventure", 
"Fullmetal Alchemist: The Sacred Star of Milos", "Puella Magi Madoka Magica", "Nana", "Case Closed", 
"Little Witch Academia", "Harlock: Space Pirate", "Yuki Yuna is a Hero", "Little Witch Academia: The Enchanted Parade", 
"Red Data Girl", "Cyborg 009 vs Devilman", "Silver Spoon", "Yu-Gi-Oh! Bonds Beyond Time", "Expelled from Paradise", 
"Samurai Flamenco", "Gunslinger Girl", "Pokemon the Movie: Diancie and the Cocoon of Destruction", 
"Pokemon the Movie: Hoopa and the Clash of Ages", "Blade of the Phantom Master", "Lagrange: The Flower of Rin-ne", 
"Ghost Tears", "Puella Magi Madoka Magica the Movie Part 1: Beginnings", "Yu-Gi-Oh Zexal", 
"Puella Magi Madoka Magica the Movie Part 1: Eternal", "Yokai Watch", "Puella Magi Madoka Magica the Movie Rebellion", 
"Persona 3 the Movie: #2 Midsummer Knight's Dream", "Gunslinger Girl -II Teatrino-", "Glitter Force", 
"Dinosaur King", "Digimon Fusion", "Beyblade Metal Fusion", "Fate/stay night: Unlimited Blade Works", 
"Hunter x Hunter", "Kill la Kill", "Fate/zero", "Pokemon: XY"];

var huluShows = ["Fairy Tail", "Tokyo Ghoul", "High School Dxd", "Assassination Classroom", "Attack on Titan", 
"Soul Eater", "D. Gray Man", "Fruits Basket", "My Hero Academia", "Shin Chan", "Cowboy Bebop", "Trigun", 
"Initial D", "Seraph of the End: Vampire Reign", "Samurai Champloo", "Claymore", "Kamisama Kiss", 
"Black Lagoon", "The Future Diary", "Overlord", "Ouran High School Host Club", "Snow White with the Red Hair", 
"Guilty Crown", "Hellsing", "Chrome Shelled Regios", "Case Closed", "Kaze no Stigma", "Danganronpa", 
"Junjo Romantica", "Noragami", "Air Gear", "Code: Breaker", "Hellsing Ultimate", "Yona of the Dawn", 
"A Certain Magical Index", "Tokyo Ravens", "The Devil is a Part Timer", "Shuffle", "Gangsta", "Date A Live", 
"Black Butler", "Shakugan no Shana", "Heroic Age", "The Wallflower", "Grimgar of Fantasy and Ash", 
"Death Parade", "Aesthetica of a Rogue Hero", "Corpse Princess", "Dragonar Academy", "Is This a Zombie?", 
"Psycho-Pass", "Afro Samurai", "Steins;Gate", "Maken-Ki! Battling Venus", "Full Metal Panic!", "Ergo Proxy", 
"Shiki", "Tenchi Muyo! War on Geminar", "Prison School", "World Break: Aria of Curse for a Holy Swordsman", 
"Shimoneta: A Boring World where the Concept of Dirty Jokes Doesn't Exist", "Devil May Cry", "Black Cat", 
"Soul Eater Not!", "Endride", "Sky Wizards Academy", "Brothers Conflict", "Attack on Titan Junior High", 
"A Certain Scientific Railgun", "Jormungand", "Lord Marksman and Vanadis", "Samurai 7", "Witchblade", 
"Mushi-Shi", "Dimension W", "Dance with Devils", "School Rumble", "Sgt Frog", "Vandread", "Desert Punk", 
"Aquarion", "Sekirei", "Blood Blockade Battlefront", "Black Blood Brothers", "The Sacred Blacksmith", 
"Black Butler: Book of Circus", "FLCL", "Big Windup", "Tokyo Majin", "Tenchi Muyo GXP", "Haganai", 
"Boku wa Tomodachi ga Sukunai", "Blood-C", "Tower of Druaga: The Aegies of Uruk", "Space Dandy", 
"The Heroic Legend of Arslan", "Nabari no Ou", "Darker than Black", "Spice and Wolf", "Gungrave", 
"Rosario + Vampire", "D-Frag!", "Absolute Duo", "Garo the Animation", "Aria: The Scarlet Ammo", "Trinity Blood", 
"Baka and Test: Summon the Beasts", "Baka no Test", "Basilisk", "Divine Gate", "Dance in the Vampire Bund", 
"Rage of Bahamut: Genesis", "Fairy Tail the Movie: Phoenix Priestess", "xxxHolic", "Aquarion EVOL", 
"Dagashi Kashi", "Sankarea", "Terror in Resonance", "Tower of Druaga: The Sword of Uruk", "Dragonaut: The Resonance", 
"Guyver: The Bioboosted Armor", "Tokyo ESP", "Gun x Sword", "Trigun: Badlands Rumble", "Afro Samurai Resurrection", 
"Shomin Sample", "The Legend of the Legendary Heroes", "Buddy Complex", "Hetalia: Axis Powers", 
"X", "Heavy Object", "Full Metal Panic? Fumoffu", "Chasshern Sins", "Unbreakable Machine-Doll", 
"Kaleido Star", "Dragon Age: Dawn of the Seeker", "Ben-To", ".hack//sign", "OniAi", "Karneval", 
"Chaos Dragon", "Laughing Under the Clouds", "Birdy the Mighy: Decode", "Luck & Logic", "Tenchi Muyo!", 
"Phantom: Requiem for the Phantom", "Last Exile", "Nobunagan", "Freezing", "Heaven's Lost Property", 
"Kingdom (2012)", "Negima!", "Michiko and Hatchin", "Ultimate Otaku Teacher", "Deadman Wonderland", 
"Barakamon", "Bamboo Blade", "Red Data Girl", "Full Metal Panic! The Second Raid", "Riddle Story of Devil", 
"Mass Effect", "Shigurui: Death Frenzy", "Chobits", "Free!", "Eden of the East", "BlazBlue: Alter Memory", 
"Serial Experiments Lain", "Fafner: Heaven and Earth", "Mongolian Chop Squad", "Eureka Seven: Astral Ocean", 
"The Slayers", "Maria the Virgin Watch", "Black Lagoon: Roberta's Blood Trail", "King of Thorn", "Pretear", 
"Negima!? Magister Negi Magi", ".hack//roots", "Tenchi Universe", "Prince of Stride: Alternative", 
"Tenchi Muyo! Ryu Ohki", "Athena: Goddess of War", "Castle Town Dandelion", "Suzuka", "Black Butler II", 
"Rampo Kitan: Game of Laplace", "Blue Gender: The Warrior", "Mikagura School Suite", "Daimidaler: Prince V.S. Penguin Empire", 
"Haibane Renmei", "TO: Eliptical Orbit", "TO: Symbiotic Planet"];

var userSearched;
var userSearchedLower;
var isOnCrunchyroll = false;
var isOnNetflix = false;
var isOnHulu = false;

var availableTags = ["07 Ghost", "11eyes", "5 Centimeters per Second", "91 Days", 
"A Bridge to the Starry Skies - Hoshizora e Kakaru Hashi", "A Dark Rabbit has Seven Lives",
"A Lull in the Sea", "Aachi & Ssipak", "Ace Attorney", "Ace of the Diamond",
"Active Raid", "Actually, I am", "Ah my Buddha!!", "Ai-Mai-Mi", 
"Ai-Mai-Mi Mousou Catastrophe", "Air Master", "AIURA", "Akagi", "Akame ga Kill!",
"AKB0048", "Alderamin on the Sky", "ALDNOAH.ZERO", "ALL OUT!!", "Amagi Brilliant Park",
"Amanchu!", "Amnesia", "Ange Vierge", "Angel Beats", "Anime De Training! Ex", 
"ANISAVA", "Anne-Happy", "Ano Natsu de Matteru", "Anohana: The Flower We Saw That Day",
"Another", "Anti-Magic Academy: The 35th Test Platoon", "Aoharu x Machinegun", 
"AOKANA: Four Rhythm Across the Blue", "Aooni The Blue Monster", 
"Arakawa Under the Bridge", "Arata the Legend", "ARGEVOLLEN", "Arpeggio of Blue Steel",
"Asura Cryin'", "Attack on Titan", "B-PROJECT", "Baby Steps", "Bakemonogatari", 
"BAKUMATSU GIJINDEN ROMAN", "BAKUON!!", "Bananya", "Battle Girls - Time Paradox",
"BBK/BRNK", "Beautiful Bones - Sakurako's Investigation-", "Beelzebub", 
"Beserk", "Beyblade", "Beyblade: Beywheelz", "Beyblade: Metal Fury", 
"Beyblade: Metal Fusion", "Beyblade: Metal Masters", "Beyond the Boundary", 
"BIG ORDER", "Black Bullet", "Black Jack", "Blade and Soul", "Bladedance of the Elementalers", 
"BLASSREITER", "Blast of Tempest", "Bleach", "Bloodivores", "Blue Exorcist", 
"Blue Spring Ride", "Blue Submarine No. 6", "Bodacious Space Pirates", 
"Boku-no-imoutowa'Osaka-okan'", "Bokurano", "BONJOUR - Sweet Love Patisserie", 
"BONO BONO", "Bottom Biting Bug", "Brave 10", "Brave Beats", "Brave Witches", 
"Break Ups", "Broken Blade", "BROTHERHOOD FINAL FANTASY XV", "Brynhildr in the Darkness", 
"BTOOOM!", "Bungo Stray Dogs", "Campione!", "Canvas 2: Niji Iro no Sketch", 
"Captain Earth", "Captain Harlock", "Cardcaptor Sakura", "Cardcaptor Sakura: The Movie", 
"Cardfight Vanguard", "Cardfight!! Vanguard Asia Circuit", "Cardfight!! Vanguard G", 
"Cardfight!! Vanguard Legion Mate", "Cardfight!! Vanguard Link Joke", "Case Closed", 
"Cat God", "Cat's Eye", "Celestial Method", "Cerberus", "Ceres, Celestial Legend", 
"Chaika - The Coffin Princess-", "Champion Joe 2", "Chance Pop Session", "Charlotte", 
"Cheating Craft", "Chi's Sweet Home - Chi's New Address", "Chihayafuru", 
"Chitose Got You!", "Chronicles of the Going Home Club", "Classroom Crisis", 
"Comet Lucifer", "Comical Psychosomatic Medicine", "Cowboy Bebop", "Crane Game Girls", 
"Crunchycast", "Crunchyroll Collection", "Crunchyroll Convention Highlights", 
"Cute High Earth Defense Club LOVE!", "Cubicle Detective Inaba", "D.Gray-man HALLOW", 
"Da Capo III", "Dai-Shogun - Great Revolution", "Dallos", "Danchigai", 
"Day Break Illusion", "DAYS", "DD Fist of the North Star", "DearS", "Deltora Quest", 
"DEMIAN", "Demon King Daimao", "Demonbane", "DENKI-GAI", "DEVIL SURVIVOR 2 THE ANIMATION", 
"Diabolik Lovers", "DIABOLIK LOVERS II: MORE,BLOOD", "Digimon Adventure", 
"Digimon Adventure 02", "Digimon Adventure tri", "Digimon Frontier", "Digimon Tamers", 
"Digimon Xros Wars", "DNA^2", "Dog & Scissors", "Dog Days", "Donyatsu", 
"Dororo Motion Magazine", "Double Hard", "DRAGON COLLECTION", "Dragon Crisis", 
"DRAMAtical Murder", "DREAM FESTIVAL!", "Durarara", "Dusk Maiden of Amnesia", "Ebiten", 
"Ef - A Tale of Melodies", "Ef - A Tale of Memories", "Encouragement of Climb", 
"Enraged to the Unidentified", "ERASED", "Erin", "ETOTAMA", "Eyeshield 21", 
"Fafner Exodus", "Fairy Musketeers", "Fairy Tail", "Familiar of Zero F", "Fantasista Doll", 
"Fantastic Adventures of Unico", "Fantastic Detective Labyrinth", 
"Fate/kaleid liner PRISMA ILLYA", "Fate/stay night", "Fate/Zero", "FIRST LOVE MONSTER", 
"Fist of the North Star", "Fist of the North Star: The Movie", "Flame of Recca", 
"FLIP FLAPPERS", "Flowers of Evil", "Flying Witch", "Folktales from Japan", 
"Food Wars! Shokugeki no Soma", "Free! - Iwatobi Swim Club", "Fullmetal Alchemist: Brotherhood", 
"Fushigi Yugi", "Fushigi Yugi OVA", "Fushigi Yugi: Eikoden", "Future Card Buddyfight", 
"GA Geijutsuka Art Design Class", "Gakuen Handsome", "Gakuen Heaven", "Galaxy Express 999", 
"Galaxy High School", "Galilei Donna", "Gankutsuou", "Garakowa -Restore the World-", 
"Gargantia on the Verdurous Planet", "Gatchaman Crowds", "GATE", "gdgd Fairies", 
"Genshiken Second Season", "Ghastly Prince Enma Burning Up", "Ghost Slayers Ayashi", 
"Ghost Stories", "Gifu Dodo!! Kanetsugu and Keiji", "Gingitsune: Messenger Fox of the Gods", 
"Gintama", "Girl Friend BETA", "Girl's High", "GIRLS und PANZER", "GJ CLUB", "Glass Mask", 
"GLASSLIP", "Go Lion", "God Eater", "God Mars", "Golden Time", "Gourmet Girl Graffiti", 
"Grimgar of Fantasy and Ash", "Group Watch", "GTO - The Animation", "Gugure! Kokkuri-san", 
"Gunbuster 2", "Gunslinger Stratos", "Gurren Lagann", "H2O: Footpritns in the Sand", 
"Hackadoll the Animation", "Haikyu!!", "Hajime no Ippo: The Fighting!", 
"Hakkenden: Eight Dogs of the East", "Hakone-chan", "Hakuoki Reimeiroku", "Hekuoki Season 1", 
"Hamatora", "Hanamaru Kindergarten", "Hanasakeru Seishonen", "Hanasaku Iroha", 
"HaNaYaMaTa", "Happiness!", "HATSUNE MIKU EXPO 2014 - New York", "Haven't You Heard? I'm Sakamoto", 
"Hayate the Combat Butler!", "Hayate the Combat Butler! (Season 1 & 2)", 
"HENNEKO - The Hentai Prince and the Story Cat", "HEROBANK", "HEROMAN", "HEYBOT!", 
"Hi-sCool! Seha Girls", "High School Fleet", "Hiiro No Kakera", "Himegoto", 
"Himouto! Umaru-chan", "hitorinoshita - The Outcast", "Holy Knight", "Horizon in the Middle of Nowhere", 
"Horror News", "Hourou Musuko Wandering Son", "Hozuki no Reitetsu", "Humanity Has Declined", 
"Hundrd", "Hunter x Hunter", "Hyakko", "I Can't Understand What My Husband Is Saying", 
"I've Always Liked You", "Inferno Cop", "Infinite Stratos", "Interlude", "Inu x Boku Secret Service", 
"Inugami-san to Nekoyama-san", "INVADERS of the REOKUJYOMA!?", "Investor Z (Motion Manga)", 
"Is It Wrong to Try to Pick Up Girls in a Dungeon?", "Is the Order a Rabbit?", "ISUCA", 
"Ixion Saga DT", "Izetta: The Last Witch", "Japanese Anime Classic Collection", "Jin Roh", "JK-MESH!", 
"JoJo's Bizarre Adventure", "JOKER", "JOKER GAME", "Jubei-chan: The Ninja Girl", "Kaasan Mom's Life", 
"Kaede New Town", "KAGEWANI", "Kaiji", "KAIJU GIRLS", "Kamigami no Asobi", "Kamisama Dolls", 
"Kanamemo", "KanColle", "Kanojo ga Flag wo Oraretara (If Her Flag Breaks)", "Keijo!!!!!!!!", 
"Kids on the Slope", "Kiitaro's yokai picture diary", "Kill la Kill", "Kimi ni Todoke - From Me To You", 
"KINMOZA!", "Kite Liberator", "KIZNAIVER", "Knuspercast", "Koihime Musou", "Kokoro Connect", 
"Komori-san Can't Decline!", "Kono Aozora ni Yakusoku wo", "KONOSUBA - God's blessing on this wonder world", 
"Kotoura-San", "Kurokan", "Kuroko's Basketball", "Kyousougiga", "La Corda d'Oro ~primo passo~ and ~secondo passo~", 
"La corda d'oro -Blue Sky-", "La storia della Arcana Famiglia", "Lady Death", "Lance N' Masques", 
"Leiji Matsumoto's OZMA", "Library War", "Lilpri", "Lily C.A.T", "Linebarrels of Iron", "LiSA TV", 
"Listen to Me, Girls, I'm Your Father!", "Little Busters!", "Little Nemo: Adventures in Slumberland", 
"Locodol", "Log Horizon", "Looking Up at the Half-Moon", "Lost Universe", "Love Lab", "Love Live! School Idol Project", 
"Love Stage!!", "Love, Chunibyo & Other Delusions", "Love, Chunibyo & Other Delusions - Heart Throb -", 
"Lovely Muuuuuuuco!", "LUPIN THE 3rd PART4", "Lupin the Third Part 1", "Lupin the Third Part 2", 
"Lupin the Third Part 3", "Lychee Light Club", "Magi", "Magic Kaito 1412", "Magic-Kyun! Renaissance", 
"MAGICA WARS", "Magical Girl Raising Project", "Magical Play", "Magical Somera-chan", "Magical Warfare", 
"Magimoji Rurumo", "Mahou Shoujo Nante Mouiidesukara", "Mahou Shoujo? Naria Girls", "Majestic Prince", 
"Majin Bone", "Makai Ouji: Devils and Realist", "makuranodanshi", "Mangirl!", "Maoyu", "Mashioiro Symphony", 
"Mazinger Edition Z", "Mazinkaiser SKL", "Medaka Box", "MEGANEBU!", "MEKAKUCITY ACTORS", "Military!", 
"Million Doll", "Milpom", "Miracle Train", "Miss Bernard said.", "Miss Machiko", "Miss Monochrome - The Animation", 
"Mizu no Kotoba", "Mob Psycho 100", "Mobile Suit GUNDAM Iron Blooded Orphans", 
"MOBILE SUIT GUNDAM UNICORN RE:0096", "Momo Kyun Sword", "momokuri", "Monogatari Second Season", 
"Mononoke", "Monster Hunter Stories: Ride On", "MONSTER MUSUME EVERYDAY LIFE WITH MONSTERS", 
"Monthly Girls' Nozaki-kun", "Moritasan wa Mukuchi", "Moyashimon", "Mr. Osomatsu", "Muromi-san", 
"MUSHI-SHI", "Mushi-Uta", "Mushibugyo", "My Little Monster", "MY Love STORY!!", 
"My Mental Choices are Completely Interfering with my School Romantic Comedy", 
"My Teen Romantic Comedy SNAFU", "Oreigairu", "Myriad Colors Phantom World", "Myself; Yourself", 
"Mysterious Girlfriend X", "Nagi no Asukara (Nagi-Asu: A Lull in the Sea)", "Naked Wolves", "Nanana's Buried Treasure", 
"NANBAKA", "Naruto", "Naruto Shippuden", "NARUTO Spin-Off: Rock Lee & His Ninja Pals", 
"NATSU NO ARASHI !", "Natsume Yujin-cho", "Natsume Yujin-cho Go", "Natsume Yujin-cho Shi", "Natsuyuki Rendezvous", 
"Nazotokine", "Nekomonogatari Black", "Neo Angelique Abyss", "NEW GAME!", "Night Raid 1931", 
"Ninja Girl & Samurai Master", "Nnija Nonsense", "Nisekoi", "Nisemonogatari", "No Game No Life", 
"No. 6", "Noblesse: Awakening", "Nobunaga Concerto", "Nobunaga the Fool", "Nobunagan", "Nogizaka Haruka no Himitsu", 
"Nogizaka Haruka no Himitsu - Purezza -", "Non Non Biyori", "Nurse Witch KOMUGI R", "Nyanbo!", 
"Nyarko-san: Another Crawling Chaos", "Occult Academy", "Ojisan and Marshamallow", "One Piece", 
"One Week Friends", "Onee-chan ga Kita", "Onimusha: Dawn of Dreams", "Ooya-san wa Shisunki!", 
"Orange", "ORECA BATTLE", "Oreimo", "Orenchi no Furo Jijo", "Oreshura", "Otome Yokai Zakuro", 
"Our Home's Fox Deity", "Outbreak Company", "OWARIMONOGATARI", "OZMAFIA!!", "Pan de Peace!", "PandoraHearts", 
"Parasyte -the maxim-", "Peeping Life", "Peeping Life TV Season 1??", "Persona4 the Golden ANIMATION", "PERSONA5 the Animation -THE DAY BREAKERS-", 
"PES: Peace Eco Smile", "Phantasy Star Online 2 The Animation", "Phantom Thief Reinya", 
"Phi Brain", "Photo Kano", "Pita-Ten", "Plastic Memories", "Please tell me! Galko-chan", 
"Polar Bear Cafe", "Poyopoyo", "Pretty Cure", "Princess Knight", "Princess Nine", "Problem Children are Coming from Another World, aren't they?", 
"PSYCHO-PASS", "Puella Magi Madoka Magica", "PUNCH LINE", "Puzzle & Dragons X", "Qualidea Code", 
"R.O.D.", "Rail Wars!", "Ramen Fighter Miki", "Re-Kan!", "Re:ZERO -Starting Life in Another World-", 
"Re:ZERO -Starting Life in Another World- Shorts", "REBORN!", "Recorder and Randsell", "ReLIFE", 
"Rewrite", "RIN-NE", "Ringing Bell", "Rio Rainbow Gate", "Ristorante Paradiso", "Robot Girls Z", 
"Rokka -Braves of the Six Flowers-", "Rowdy Sumo Wrestler Matsutaro", "Rozen Maiden", "Rozen Maiden Zurückspulen", 
"Ruroni Kenshin", "RWBY", "Sabagebu! -Survival Game Club!-", "Saekano -How to Raise a Boring Girlfriend-", 
"Sailor Moon Crystal", "Saint Seiya - Soul of Gold", "Saint Seiya Hades", "Saint Seiya Omega", "Saint Seiya The Lost Canvas", 
"Saint Seiya: Sanctuary", "Saki", "Saki Episode of Side A", "Sakura Trick", "Samurai Flamenco", 
"Samurai Jam-Bakumatsu Rock", "Samurai Pizza Cats", "Samurai Warriors", "Say 'I Love You'", 
"School Days", "SCHOOL-LIVE!", "Schwarzes Marken", "Scorching Ping Pong Girls", "Sea Prince and the Fire Child", 
"Seitokai No Ichizon - Student Councils Discretion", "Sekai Ichi Hatsukoi - World's Greatest First Love", 
"Sekko Boys", "Sengoku Collection (Parallel World Samurai)", "Senyu", "Servant x Service", 
"Shamanic Princess", "She and Her Cat -Everything Flows-", "Sherlock Hound", "Shin Atashinchi", 
"Shin Koihime Musou", "Shin Koihime Musou - Otome Tairan", "Shin Sekai Yori (From the New World)", 
"Shingu: Secret of the Stellar Wars", "SHIROBAKO", "SHOKU-KING (Motion Manga)", "Shonen Ashibe GO! GO! Goma-chan", 
"Show By Rock!!", "Showa Genroku Rakugo Shinju", "Shugo Chara", "Silver Spoon", "Sin The Movie", 
"SKET Dance", "Sketchbook ~full color's~", "Skip Beat!", "Slam Dunk", "Soni-Ani: SUPER SONICO THE ANIMATION", 
"Sound of the Sky", "Sound! Euphonium", "Hibike! Euphonium", "Space Adventure Cobra", "Space Brothers", 
"SPACE PATROL LULUCO", "Space Pirate Mito", "Sparrow's Hotel", "Squid Girl", "Star Driver", 
"Stella Women’s Academy, High School Division Class C3", "Straight Title Robot Anime", 
"Strange+", "Street Fighter II The Animated Movie", "Strike the Blood", "Sunday Without God", 
"Super Robot Wars: Original Generation", "Sweet Blue Flowers", "sweetness and lightning", 
"Sword Art Online", "Symphogear", "Tabimachi Lateshow", "Taboo Tattoo", "Takamiya Nasuno Desu!", 
"Tanaka-kun is Always Listless", "Tantei Team KZ Jiken Note", "Tari Tari", "Teekyu", "Tegami Bachi Letter Bee", 
"Tenjho Tenge", "TERRAFORMARS", "Tesagure! Bukatsumono", "The Ambition of Oda Nobuna", "The Ancient Magus' Bride", 
"The Asterisk War", "The Comic Artist and His Assistants", "The Diary of Ochibi (Motion Manga)", 
"The File of Young Kindaichi Returns", "The Fruit of Grisaia", "The Galaxy Railways: A Letter from the Abandoned Planet", 
"The Highschool Life of a Fundanshi", "The Idol Master", "The Irregular at Magic High School", 
"The Kawaii Complex Guide to Manors and Hostel Behavior", "The Knight in the Area", "The Live Show", 
"The Lost Village", "The Melody of Oblivion", "The Morose Mononokean", "The Nameko Families", 
"The Perfect Insider", "The Pet Girl of Sakurasou", "The Pilot's Love Song", "The Place Promised In Our Early Days", 
"The Prince of Tennis II", "The Prince of Tennis II OVA vs Genius 10", "The Princess and the Pilot", 
"The Rose of Versailles", "The Severing Crime Edge", "The Tenth Prism (Motion Manga)", "The Testament of Sister New Devil", 
"The Tower of DRUAGA -the Aegis of URUK-", "The Tower of DRUAGA -the Sword of URUK-", 
"THE UNLIMITED Hyobu Kyosuke", "The World God Only Knows", "The World is Still Beautiful", "This Art Club Has a Problem!", 
"This Boy is a Professional Wizard", "This Boy Suffers from Crystalization", "Thunderbolt Fantasy", 
"Tiger Mask W", "Time Bokan 24", "Time of Eve", "TO BE HERO", "Tonari no Seki-kun: The Master of Killing Time", 
"Tonkatsu DJ Agetaro", "Tono to Issho", "Toradora!", "Toriko", "Total Eclipse", "Touken Ranbu - Hanamaru", 
"Toward the Terra", "Traveling Daru", "Triage X", "Tribe Cool Crew", "Trickster", "TRINITY SEVEN", 
"Tsukimonogatari", "Tsuritama", "Twin Angel: Twinkle Princess", "Twin Star Exorcists", "Un-Go", 
"Unico In the Island of Magic", "Unlimited Fafnir", "Upotte!!", "Urawa no Usagi-chan", "Usagi Drop", 
"Usakame", "Ushio and Tora", "Uta no Prince Sama", "Utakoi", "Utawarerumono The False Faces", 
"Valerian and Laureline", "Vividred Operation", "Voices of a Distant Star", "Wagamama High Spec", 
"Wagnaria!!", "Wakaba Girl", "Wakakozake", "Wake Up, Girls!", "Walkure Romanze", "Wanna be the Strongest in the World", 
"WATAMOTE ~No Matter How I Look at It, It’s You Guys Fault I’m Not Popular", "We, Without Wings - under the innocent sky", 
"Web Ghosts PiPoPa", "When Supernatural Battles Become Commonplace", "White Album", "White Album 2", 
"Wish Upon the Pleiades", "Witch Craft Works", "Wizard Barristers", "Wolf Girl and Black Prince", 
"Wonder Momo", "Wooser's Hand-to-Mouth Life", "Wooser's Hand-to-Mouth Life: Phantasmagoric Arc", 
"World Break: Aria of Curse for a Holy Swordsman", "World Conquest Zvezda Plot", "World Fool News", 
"World Trigger", "WWWW.WAGNARIA!!", "Yakitate!! Japan", "Yamada-kun and the Seven Witches", 
"Yamishibai: Japanese Ghost Stories", "Yokuwakaru Gendai Maho", "Yona of the Dawn", "Yonna in the Solitary Fortress", 
"You and Me", "You and Me 2", "You're Being Summoned, Azazel", "Young Black Jack", "Your lie in April", 
"Yowamushi Pedal", "Yu-Gi-Oh!", "Yu-Gi-Oh! 5D's", "Yu-Gi-Oh! GX", "YUKI YUNA IS A HERO", "Yuri!!! On ICE", 
"Yurumates3Dei", "YuruYuri", "YUYUSHIKI", "Z/X IGNITION", "Zapuni", "Zatch Bell!", "Zettai Boei Leviatan", 
"Zombie Loan", "The Seven Deadly Sins", "Attack on Titan", "Fairy Tail", "Magi: Adventure of Sinbad", 
"Sword Art Online", "Ruroni Kenshin", "Blue Exorcist", "Ajin: Demi-Human", "Naruto", "Robotech", 
"Bleach", "Magi: The Kingdom of Magic", "Sword Art Online II", "Kuromukuro", "Soul Eater", 
"Ouran High School Host Club", "Gurren Lagann", "Your lie in April", "Pokemon: Indigo League", 
"Magi: The Labyrinth of Magic", "Black Butler", "Rosario + Vampire", "The Irregular at Magic High School", 
"Knights of Sidonia", "Durarara!!", "Aldnoah.Zero", "K", "InuYasha", "Durarara!!X2", "Gargantia on the Verdurous Planet", 
"Moribito: Guardian of the Spirit", "Mushi-Shi", "Nura: Rise of the Yokai Clan", "Digimon Adventure", 
"Fullmetal Alchemist: The Sacred Star of Milos", "Puella Magi Madoka Magica", "Nana", "Case Closed", 
"Little Witch Academia", "Harlock: Space Pirate", "Yuki Yuna is a Hero", "Little Witch Academia: The Enchanted Parade", 
"Red Data Girl", "Cyborg 009 vs Devilman", "Silver Spoon", "Yu-Gi-Oh! Bonds Beyond Time", "Expelled from Paradise", 
"Samurai Flamenco", "Gunslinger Girl", "Pokemon the Movie: Diancie and the Cocoon of Destruction", 
"Pokemon the Movie: Hoopa and the Clash of Ages", "Blade of the Phantom Master", "Lagrange: The Flower of Rin-ne", 
"Ghost Tears", "Puella Magi Madoka Magica the Movie Part 1: Beginnings", "Yu-Gi-Oh Zexal", 
"Puella Magi Madoka Magica the Movie Part 1: Eternal", "Yokai Watch", "Puella Magi Madoka Magica the Movie Rebellion", 
"Persona 3 the Movie: #2 Midsummer Knight's Dream", "Gunslinger Girl -II Teatrino-", "Glitter Force", 
"Dinosaur King", "Digimon Fusion", "Beyblade Metal Fusion", "Fate/stay night: Unlimited Blade Works", 
"Hunter x Hunter", "Kill la Kill", "Fate/zero", "Pokemon: XY", "Fairy Tail", "Tokyo Ghoul", "High School Dxd", "Assassination Classroom", "Attack on Titan", 
"Soul Eater", "D. Gray Man", "Fruits Basket", "My Hero Academia", "Shin Chan", "Cowboy Bebop", "Trigun", 
"Initial D", "Seraph of the End: Vampire Reign", "Samurai Champloo", "Claymore", "Kamisama Kiss", 
"Black Lagoon", "The Future Diary", "Overlord", "Ouran High School Host Club", "Snow White with the Red Hair", 
"Guilty Crown", "Hellsing", "Chrome Shelled Regios", "Case Closed", "Kaze no Stigma", "Danganronpa", 
"Junjo Romantica", "Noragami", "Air Gear", "Code: Breaker", "Hellsing Ultimate", "Yona of the Dawn", 
"A Certain Magical Index", "Tokyo Ravens", "The Devil is a Part Timer", "Shuffle", "Gangsta", "Date A Live", 
"Black Butler", "Shakugan no Shana", "Heroic Age", "The Wallflower", "Grimgar of Fantasy and Ash", 
"Death Parade", "Aesthetica of a Rogue Hero", "Corpse Princess", "Dragonar Academy", "Is This a Zombie?", 
"Psycho-Pass", "Afro Samurai", "Steins;Gate", "Maken-Ki! Battling Venus", "Full Metal Panic!", "Ergo Proxy", 
"Shiki", "Tenchi Muyo! War on Geminar", "Prison School", "World Break: Aria of Curse for a Holy Swordsman", 
"Shimoneta: A Boring World where the Concept of Dirty Jokes Doesn't Exist", "Devil May Cry", "Black Cat", 
"Soul Eater Not!", "Endride", "Sky Wizards Academy", "Brothers Conflict", "Attack on Titan Junior High", 
"A Certain Scientific Railgun", "Jormungand", "Lord Marksman and Vanadis", "Samurai 7", "Witchblade", 
"Mushi-Shi", "Dimension W", "Dance with Devils", "School Rumble", "Sgt Frog", "Vandread", "Desert Punk", 
"Aquarion", "Sekirei", "Blood Blockade Battlefront", "Black Blood Brothers", "The Sacred Blacksmith", 
"Black Butler: Book of Circus", "FLCL", "Big Windup", "Tokyo Majin", "Tenchi Muyo GXP", "Haganai", 
"Boku wa Tomodachi ga Sukunai", "Blood-C", "Tower of Druaga: The Aegies of Uruk", "Space Dandy", 
"The Heroic Legend of Arslan", "Nabari no Ou", "Darker than Black", "Spice and Wolf", "Gungrave", 
"Rosario + Vampire", "D-Frag!", "Absolute Duo", "Garo the Animation", "Aria: The Scarlet Ammo", "Trinity Blood", 
"Baka and Test: Summon the Beasts", "Baka no Test", "Basilisk", "Divine Gate", "Dance in the Vampire Bund", 
"Rage of Bahamut: Genesis", "Fairy Tail the Movie: Phoenix Priestess", "xxxHolic", "Aquarion EVOL", 
"Dagashi Kashi", "Sankarea", "Terror in Resonance", "Tower of Druaga: The Sword of Uruk", "Dragonaut: The Resonance", 
"Guyver: The Bioboosted Armor", "Tokyo ESP", "Gun x Sword", "Trigun: Badlands Rumble", "Afro Samurai Resurrection", 
"Shomin Sample", "The Legend of the Legendary Heroes", "Buddy Complex", "Hetalia: Axis Powers", 
"X", "Heavy Object", "Full Metal Panic? Fumoffu", "Chasshern Sins", "Unbreakable Machine-Doll", 
"Kaleido Star", "Dragon Age: Dawn of the Seeker", "Ben-To", ".hack//sign", "OniAi", "Karneval", 
"Chaos Dragon", "Laughing Under the Clouds", "Birdy the Mighy: Decode", "Luck & Logic", "Tenchi Muyo!", 
"Phantom: Requiem for the Phantom", "Last Exile", "Nobunagan", "Freezing", "Heaven's Lost Property", 
"Kingdom (2012)", "Negima!", "Michiko and Hatchin", "Ultimate Otaku Teacher", "Deadman Wonderland", 
"Barakamon", "Bamboo Blade", "Red Data Girl", "Full Metal Panic! The Second Raid", "Riddle Story of Devil", 
"Mass Effect", "Shigurui: Death Frenzy", "Chobits", "Free!", "Eden of the East", "BlazBlue: Alter Memory", 
"Serial Experiments Lain", "Fafner: Heaven and Earth", "Mongolian Chop Squad", "Eureka Seven: Astral Ocean", 
"The Slayers", "Maria the Virgin Watch", "Black Lagoon: Roberta's Blood Trail", "King of Thorn", "Pretear", 
"Negima!? Magister Negi Magi", ".hack//roots", "Tenchi Universe", "Prince of Stride: Alternative", 
"Tenchi Muyo! Ryu Ohki", "Athena: Goddess of War", "Castle Town Dandelion", "Suzuka", "Black Butler II", 
"Rampo Kitan: Game of Laplace", "Blue Gender: The Warrior", "Mikagura School Suite", "Daimidaler: Prince V.S. Penguin Empire", 
"Haibane Renmei", "TO: Eliptical Orbit", "TO: Symbiotic Planet"];

var uniq = availableTags.reduce(function(a,b){
    if (a.indexOf(b) < 0 ) a.push(b);
    return a;
  },[]);

$(function() {
  
    $("#searchBox").autocomplete({
      source: uniq
    });
  });

function getUserSearch() {
  userSearched = document.getElementById("searchBox").value;
}

function searchCrunchyroll() {
  isOnCrunchyroll = false;
  var searchResult = crunchyrollShows.indexOf(userSearched);
  if (searchResult > -1) {
    isOnCrunchyroll = true;
  }
}

function searchNetflix() {
  isOnNetflix = false;
  var searchResult = netflixShows.indexOf(userSearched);
  if (searchResult > -1) {
    isOnNetflix = true;
  }
}

function searchHulu() {
  isOnHulu = false;
  var searchResult = huluShows.indexOf(userSearched);
  if (searchResult > -1) {
    isOnHulu = true;
  }
}

function returnResult() {
  
  getUserSearch();
  searchCrunchyroll();
  searchNetflix();
  searchHulu();
  
  if (isOnCrunchyroll === true && isOnNetflix === true && isOnHulu === true) {
    $('#result').html(userSearched + ' is on Crunchyroll, Netflix, and Hulu!');
  } else if (isOnCrunchyroll === true && isOnNetflix == true && isOnHulu === false) {
    $('#result').html(userSearched + ' is on Crunchyroll and Netflix!');
  } else if (isOnCrunchyroll === true && isOnNetflix == false && isOnHulu === true) {
    $('#result').html(userSearched + ' is on Crunchyroll and Hulu!');
  } else if (isOnCrunchyroll === false && isOnNetflix == true && isOnHulu === true) {
    $('#result').html(userSearched + ' is on Netflix, and Hulu!');
  } else if (isOnCrunchyroll === true && isOnNetflix == false && isOnHulu === false) {
    $('#result').html(userSearched + ' is on Crunchyroll!');
  } else if (isOnCrunchyroll === false && isOnNetflix == true && isOnHulu === false) {
    $('#result').html(userSearched + ' is on Netflix!');
  } else if (isOnCrunchyroll === false && isOnNetflix == false && isOnHulu === true) {
    $('#result').html(userSearched + ' is on Hulu!');
  } else {
    $('#result').html(userSearched + ' cannot be found on Crunchyroll, Hulu, or Netflix.');
  }
}

$("#searchBox").keypress(function(e) {
    if(e.which == 13) {
        returnResult();	
    }
});